# These are supported funding model platforms

github: [Xx7Navin7xX]
ko_fi: navin007
custom:
  - https://paypal.me/Navin007143
  - https://razorpay.me/@navin007
  - upi://pay?pa=navinbalaji004@okhdfcbank&pn=Navin%20Balaji
